services:
  postgre:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dailydiet
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dailydiet-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "clesyonph@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - 16543:80
    depends_on:
      - postgre
    networks:
      - dailydiet-network

volumes:
  postgres-data:

networks:
  dailydiet-network:
    driver: bridge
