[tool.poetry]
name = "flask-daily-diet-api"
version = "0.1.0"
description = "API para controle de dieta diária"
authors = ["Cleyson <cleysonph@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.0"
python-dotenv = "^1.0.0"


[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
