"""create meals table

Revision ID: c27fa7ee9f18
Revises: 
Create Date: 2024-01-18 18:14:56.970520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c27fa7ee9f18"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("in_diet", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meals")
    # ### end Alembic commands ###
